### ISSUE TITLE
スタート画面とゲームオーバー画面についてです。

### ISSUE THREAD

**Issue by HamadaKenta** [konan-pbl-2018/teamE#10]
現在、スタート画面とゲームオーバ画面を画像と別々に用意し、それを表示して何かキーを押したらその画像が消えゲーム画面へ移行するということをしたいです。

画像を全体に表示する方法。
何かキーを押したら表示した画像が消える方法。
条件を満たしたら画像が現れる方法。

以上の3点についてご教示ください。

**Comment by r-ishitani** [comment]
スタート画面やエンディング画面の実装には画面の遷移が必要なので, TemplateShooting2DMultiStatesクラスのコンストラクタ付近のコードをTemplateMazeGame2Dクラスにまずはコピペして持っていってください. (ただし, その際にコンストラクタの名前はクラス名と一致するように変更してください)

画像に表示にはRWTImageクラスのインスタンスを作ってください (インスタンス生成の際に使いたい画像のパスを渡す)
RWTImageクラスのインスタンスはそれぞれの画像を表示させたい場面に対応するコンテナクラスのbuildメソッド内で生成してください.

何かキーを押したら表示した画像が消える方法と, 条件を満たしたら画像が現れる方法に関しては,
画面の切り替えを行う際に対応するコンテナに切り替わると思うので, それで実現ができるかと思います.
