### ISSUE TITLE
先ほどの画面遷移についての質問です

### ISSUE THREAD

**Issue by HamadaKenta** [konan-pbl-2018/teamE#11]
コピペしてメインクラスに持ってきて、型名を変えるところでつまずいてしましました。
型名を変えても赤線が消えないところがいくつかあります。

申し訳ありませんが見てもらえないでしょうか。

**Comment by n-nitta** [comment]
了解しました。

**Comment by n-nitta** [comment]
SimpleMazeGameを修正しました。試してみてください。

**Comment by r-ishitani** [comment]
画面遷移について確認できました.
