### ISSUE TITLE
クリア画面を表示させたいです

### ISSUE THREAD

**Issue by HamadaKenta** [konan-pbl-2018/teamE#13]
スコアが一定の値を超えたら、画面全体に上書きするような感じで表示したいです。
どうすれば良いでしょうか。

**Comment by r-ishitani** [comment]
対応したところ, ゲーム画面の上にクリア用の画像Spriteクラスを使って画面全体に上書きするように表示したいと見受けられたので, もしそうするのならばコンストラクタでscale指定とsetPositionで場所指定して画面全体に上書きするように表示させること自体は一応はできると思います.
