### ISSUE TITLE
一定時間ごとにランダムな動きをさせたいです。

### ISSUE THREAD

**Issue by HamadaKenta** [konan-pbl-2018/teamE#3]
以下のコードで実装しました。
if((int)(5*(Math.random()))==0){
			setVelocity(0.0,0.0);
		}
		else if((int)(5*(Math.random()))==1) {
			setVelocity(0,-4.5);
		}
		else if((int)(5*(Math.random()))==2) {
			setVelocity(4.5,0);
		}
		else if((int)(5*(Math.random()))==3) {
			setVelocity(0.0,4.5);
		}
		else if((int)(5*(Math.random()))==4) {
			setVelocity(-4.5,0);
		}
ランダムで０～４の数値を取り、
それぞれ、止まる、上へ、下へ、右へ、左へという動きを割り当てました。

しかし、間隔が短すぎたのか同じ場所でガタガタと震えるだけでした。
何か良い方法はないでしょうか。

**Comment by r-ishitani** [comment]
間隔については先ほど説明した通り引数intervalを利用して測ることが出来ます.
また, 乱数はif文の条件式中で毎回取得するのではなくて, if文前に1回取得したものを変数に入れておき,
その変数を用いて判定を行ってください.
